version: '3'

services:
  db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: authentication
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
  cache:
    image: redis:alpine
    ports:
      - '6379:6379'